export const cocktails = [
  {
    id: "krakn_stormy",
    name: "Krak'n Stormy",
    category: "classic",
    ingredients: [
      { name: "Sirop Falernum" },
      { name: "Jus de citron vert" },
      { name: "Quartiers de citron vert", quantity: "2" },
      { name: "Rhum Kraken" },
      { name: "Ginger Beer" },
    ],
  },
  {
    id: "maree_noire",
    name: "Marée noire",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "traquenard_en_douceur",
    name: "Traquenard en douceur",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "riviere_pourpre",
    name: "Rivière pourpre",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "ptit_biscuit",
    name: "P'tit biscuit",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "le_petit_pres",
    name: "Le petit près",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "kernel_daddy_cage",
    name: "Kernel daddy cage",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "ca_remet_le_facteur_sur_le_velo",
    name: "Ça remet le facteur sur le vélo",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "bdsm",
    name: "BDSM",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "devils_deal",
    name: "Devil's deal",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "anus_de_fer",
    name: "Anus de fer",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "le_bon_dej",
    name: "Le bon déj'",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "blue_dildo",
    name: "Blue dildo",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "la_catin_des_prebendes",
    name: "La catin des prébendes",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "il_est_frais_le_gardon",
    name: "Il est frais le gardon",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "le_mama",
    name: "Le mama",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "fais_confiance",
    name: "Fais confiance",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "foie_de_coton",
    name: "Foie de coton",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "desperate_ass_wives",
    name: "Desperate ass wives",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "no_name",
    name: "???",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "ca_rhabille_la_gamine",
    name: "Ça rhabille la gamine",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "sperm_on_the_bitch",
    name: "Sperm on the bitch",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "tiniac",
    name: "Tiniac",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "suze_moi_si_tu_peux",
    name: "Suze-moi si tu peux",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "lady_fist",
    name: "Lady fist",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "carapute",
    name: "Carapute",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "fucking_bloody_thursday",
    name: "Fucking bloody thursday",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "le_petit_fiak",
    name: "Le petit fiak",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
  {
    id: "chico_mou",
    name: "Chico mou",
    category: "homemade",
    ingredients: [{ name: "" }],
  },
];
